import { describe, expect, it } from "vitest";
import { crc32, deflateRawSync } from "node:zlib";
import { parseSlicerImport } from "../src/domain/impressao3d/slicer-import";

/**
 * O importador de fatiador contra arquivos 3MF DE VERDADE.
 *
 * O `.3mf` é a exportação nativa da Bambu Lab — a impressora que está na
 * oficina. O parser antigo fazia `buffer.toString("utf8")` num ZIP e procurava
 * ";FLAVOR" como texto: em conteúdo comprimido isso nunca aparece, então todo
 * 3MF real devolvia peso e tempo `undefined` calado.
 *
 * Isso importa porque sem tempo o custo de máquina e de energia saem ZERO, e a
 * peça é vendida abaixo do custo. Um teste com texto simulando 3MF passaria e
 * não provaria nada — daí montar o ZIP de verdade aqui.
 */

type Arquivo = { nome: string; conteudo: Buffer | string };

/** Escreve um ZIP mínimo (deflate) para os testes não dependerem de binário no repo. */
function montarZip(arquivos: Arquivo[]): Buffer {
  const locais: Buffer[] = [];
  const centrais: Buffer[] = [];
  let offset = 0;

  for (const { nome, conteudo } of arquivos) {
    const bruto = Buffer.isBuffer(conteudo) ? conteudo : Buffer.from(conteudo, "utf8");
    const comprimido = deflateRawSync(bruto);
    const nomeBuf = Buffer.from(nome, "utf8");
    const soma = crc32(bruto);

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4); // versão necessária
    local.writeUInt16LE(8, 8); // método: deflate
    local.writeUInt32LE(soma, 14);
    local.writeUInt32LE(comprimido.byteLength, 18);
    local.writeUInt32LE(bruto.byteLength, 22);
    local.writeUInt16LE(nomeBuf.byteLength, 26);
    locais.push(local, nomeBuf, comprimido);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(8, 10);
    central.writeUInt32LE(soma, 16);
    central.writeUInt32LE(comprimido.byteLength, 20);
    central.writeUInt32LE(bruto.byteLength, 24);
    central.writeUInt16LE(nomeBuf.byteLength, 28);
    central.writeUInt32LE(offset, 42);
    centrais.push(central, nomeBuf);

    offset += 30 + nomeBuf.byteLength + comprimido.byteLength;
  }

  const corpo = Buffer.concat(locais);
  const diretorio = Buffer.concat(centrais);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(arquivos.length, 8);
  eocd.writeUInt16LE(arquivos.length, 10);
  eocd.writeUInt32LE(diretorio.byteLength, 12);
  eocd.writeUInt32LE(corpo.byteLength, 16);
  return Buffer.concat([corpo, diretorio, eocd]);
}

const MODELO = "<?xml version='1.0'?><model/>";

const gcodeBambu = (h: number, m: number, s: number, g: string) =>
  [
    "; generated by BambuStudio 1.9.0",
    ";FLAVOR:Marlin",
    `; estimated printing time (normal mode) = ${h}h ${m}m ${s}s`,
    `; total filament used [g] = ${g}`,
    "G1 X0 Y0",
  ].join("\n");

const sliceInfo = (placas: { i: number; segundos: number; gramas: string }[]) =>
  `<?xml version="1.0"?><config>${placas
    .map(
      (p) =>
        `<plate><metadata key="index" value="${p.i}"/>` +
        `<metadata key="prediction" value="${p.segundos}"/>` +
        `<metadata key="weight" value="${p.gramas}"/></plate>`,
    )
    .join("")}</config>`;

describe("importar .3mf de verdade (ZIP)", () => {
  it("lê tempo e peso de uma placa pelo slice_info", () => {
    const zip = montarZip([
      { nome: "3D/3dmodel.model", conteudo: MODELO },
      { nome: "Metadata/plate_1.gcode", conteudo: gcodeBambu(3, 42, 15, "128.47") },
      { nome: "Metadata/slice_info.config", conteudo: sliceInfo([{ i: 1, segundos: 13335, gramas: "128.47" }]) },
    ]);

    const r = parseSlicerImport(zip, "peca.3mf", "model/3mf");
    expect(r.parser).toBe("BambuStudioParser");
    // 3h42m15s = 13335 s. Era `undefined` antes.
    expect(r.data.totalTimeSeconds).toBe(13335);
    expect(r.data.totalWeightG).toBeCloseTo(128.47, 2);
    expect(r.data.plates).toHaveLength(1);
    expect(r.data.missing).toEqual([]);
  });

  it("soma as placas e mantém cada uma separada", () => {
    const zip = montarZip([
      { nome: "3D/3dmodel.model", conteudo: MODELO },
      {
        nome: "Metadata/slice_info.config",
        conteudo: sliceInfo([
          { i: 1, segundos: 3600, gramas: "50.5" },
          { i: 2, segundos: 1800, gramas: "20.25" },
        ]),
      },
    ]);

    const r = parseSlicerImport(zip, "duas.3mf", "model/3mf");
    expect(r.data.totalTimeSeconds).toBe(5400);
    expect(r.data.totalWeightG).toBeCloseTo(70.75, 2);
    // Separadas importa: cada placa é uma impressão, com consumo próprio.
    expect(r.data.plates.map((p) => p.timeSeconds)).toEqual([3600, 1800]);
    expect(r.data.plates.map((p) => p.name)).toEqual(["plate-1", "plate-2"]);
  });

  it("cai no G-code quando não há slice_info", () => {
    const zip = montarZip([
      { nome: "3D/3dmodel.model", conteudo: MODELO },
      { nome: "Metadata/plate_1.gcode", conteudo: gcodeBambu(1, 30, 0, "42.5") },
    ]);

    const r = parseSlicerImport(zip, "sem-info.3mf", "model/3mf");
    expect(r.data.totalTimeSeconds).toBe(5400);
    expect(r.data.totalWeightG).toBeCloseTo(42.5, 2);
  });

  it("recusa zip bomb em vez de estourar a memória", () => {
    // 200 MB de zeros comprimem para poucos KB. O teto é 120 MB.
    const zip = montarZip([
      { nome: "3D/3dmodel.model", conteudo: MODELO },
      { nome: "Metadata/enorme.gcode", conteudo: Buffer.alloc(200 * 1024 * 1024) },
    ]);
    expect(() => parseSlicerImport(zip, "bomba.3mf", "model/3mf")).toThrow(/limite de expansão/i);
  });

  it("recusa arquivo que não é ZIP nem G-code", () => {
    const lixo = Buffer.from("isso nao e um zip de jeito nenhum", "utf8");
    // Sem PK na frente vai para o parser de G-code, que não acha nada.
    const r = parseSlicerImport(lixo, "lixo.3mf", "model/3mf");
    expect(r.data.totalTimeSeconds).toBeUndefined();
    expect(r.data.missing).toContain("totalTimeSeconds");
  });

  it("continua lendo G-code solto, sem regressão", () => {
    const r = parseSlicerImport(Buffer.from(gcodeBambu(2, 3, 4, "42.5"), "utf8"), "peca.gcode");
    expect(r.parser).toBe("GenericGCodeParser");
    expect(r.data.totalTimeSeconds).toBe(7384);
    expect(r.data.totalWeightG).toBeCloseTo(42.5, 2);
  });
});

/**
 * Formatos que os fatiadores realmente escrevem.
 *
 * A regex antiga aceitava só `chave: valor`. Bambu e PrusaSlicer escrevem
 * `chave = valor`, e o Cura escreve o tempo em segundos puros. Nos três casos o
 * resultado era peso ou tempo perdido — e tempo perdido zera custo de máquina e
 * de energia, o que faz a peça sair abaixo do custo.
 */
describe("separadores e unidades de cada fatiador", () => {
  const casos: { nome: string; texto: string; segundos: number; gramas?: number }[] = [
    {
      nome: "Bambu Studio (separador =)",
      texto: "; estimated printing time (normal mode) = 3h 42m 15s\n; total filament used [g] = 128.47",
      segundos: 13335,
      gramas: 128.47,
    },
    {
      nome: "PrusaSlicer (separador = sem 'total')",
      texto: "; estimated printing time (normal mode) = 1h 5m 30s\n; filament used [g] = 33.2",
      segundos: 3930,
      gramas: 33.2,
    },
    {
      nome: "formato antigo com dois-pontos",
      texto: "; estimated printing time: 2h 3m 4s\n; filament used [g]: 42.5",
      segundos: 7384,
      gramas: 42.5,
    },
    {
      nome: "Cura (tempo em segundos puros)",
      texto: ";TIME:3600\n;Filament used: 12.5m",
      segundos: 3600,
    },
    {
      nome: "gramas declaradas no valor",
      texto: "; estimated printing time = 0h 10m 0s\n; filament used = 8.4g",
      segundos: 600,
      gramas: 8.4,
    },
    {
      nome: "vírgula decimal",
      texto: "; estimated printing time = 0h 30m 0s\n; total filament used [g] = 15,75",
      segundos: 1800,
      gramas: 15.75,
    },
  ];

  for (const caso of casos) {
    it(`lê ${caso.nome}`, () => {
      const r = parseSlicerImport(Buffer.from(caso.texto, "utf8"), "peca.gcode");
      expect(r.data.totalTimeSeconds).toBe(caso.segundos);
      if (caso.gramas !== undefined) {
        expect(r.data.totalWeightG).toBeCloseTo(caso.gramas, 2);
      }
    });
  }

  it("não confunde METROS com GRAMAS", () => {
    // O Cura reporta comprimento: `;Filament used: 12.5m` são 12,5 METROS.
    // Lidos como gramas, o material sai ~3x menor (12,5 m de PLA 1,75 mm
    // pesam ~37 g) e a peça é orçada com um terço do filamento que gasta.
    const r = parseSlicerImport(Buffer.from(";TIME:3600\n;Filament used: 12.5m", "utf8"), "p.gcode");
    expect(r.data.totalWeightG).toBeUndefined();
    expect(r.data.missing).toContain("totalWeightG");
    // O tempo, esse sim, tem que sair certo.
    expect(r.data.totalTimeSeconds).toBe(3600);
  });

  it("tempo zero nunca passa como tempo válido", () => {
    // Sem tempo o custo de máquina e de energia saem zerados. Melhor ausente
    // (que a tela recusa) do que zero disfarçado de número.
    const r = parseSlicerImport(Buffer.from("; sem nada aqui\nG1 X0", "utf8"), "peca.gcode");
    expect(r.data.totalTimeSeconds).toBeUndefined();
    expect(r.data.missing).toContain("totalTimeSeconds");
  });
});
