/**
 * O MODO DE EXEMPLO da TV: `/tv/maquinas?demo=cheio` e `?demo=hoje`.
 *
 * Serve para testar o aparelho antes de parear (ler de longe, ver se cabe,
 * desligar e ligar) e para fotografar. Nunca usa crachá nem chama rota: o dado
 * está aqui, no formato EXATO do contrato v2 que a função viva devolve — nada
 * que a função não mande hoje (sem data de prazo na fila, sem "1/2" pronto).
 * A aba "EXEMPLO SIMULADO — NÃO É A OFICINA DE HOJE" fica no alto e o selo
 * nunca diz AO VIVO sem o adjetivo SIMULADO.
 *
 * CHEIO é o dia de exemplo INVENTADO da maquete (tv-grafica.html, estado
 * `cheio`), traduzido do dado cru para o que a função devolveria: as mesmas OS,
 * horas e filas; só os nomes de produto são reais (produtos.nome, 01/10/2026).
 * HOJE é o retorno REAL de tv_painel_maquinas() em 01/10/2026 19:54 de Macapá
 * (tests/fixtures/tv-painel-hoje.json): 2 OS em entrada, 0 apontamentos.
 *
 * Regra da parede, inclusive aqui: nenhum custo, preço, pagamento ou cliente.
 */

import type { PainelDaOficina } from "./painel";

export type ModoDeExemplo = "cheio" | "hoje";

export function modoDeExemplo(valor: unknown): ModoDeExemplo | undefined {
  return valor === "cheio" || valor === "hoje" ? valor : undefined;
}

export function etiquetaDoExemplo(modo: ModoDeExemplo): string {
  return modo === "hoje"
    ? "EXEMPLO SIMULADO (RETRATO DE 01/10) — NÃO É A OFICINA DE HOJE"
    : "EXEMPLO SIMULADO — NÃO É A OFICINA DE HOJE";
}

const IMP = "b77ec8f1-f336-4433-9b49-03c34db4183e";
const REC = "e2c92d0d-3b74-4240-8633-5428ff00dfc3";
const CO2 = "da13a08f-3f53-4974-9d41-cccad44a9ab5";
const FIB = "c67b9750-b7a9-43c7-84c1-2953ed15ecde";
const D3 = "39807c59-d6da-42f4-9072-9540978cd3d4";

/* 15:25:20 em Macapá (UTC-3) = 18:25:20Z. Horas locais escritas como a função escreve. */
export const EXEMPLO_CHEIO: PainelDaOficina = {
  versao: 2,
  gerado_em: "2026-10-01T18:25:20+00:00",
  hoje_local: "2026-10-01",
  fuso: "America/Belem",
  intervalo_s: 60,
  dentro_do_expediente: true,
  registro: {
    apontamentos_hoje: 4,
    apontamentos_abertos: 1,
    ultimo_apontamento_local: "14:05",
    ultimo_registro_local: "14:05",
    sem_apontamento_em_7_dias: false,
    jobs_3d_hoje: 0,
    ultimo_job_3d_local: null,
  },
  rodando: { total: 1, de: 5 },
  cartoes: {
    atrasadas: {
      total: 2,
      nas_maquinas: 2,
      fora: 0,
      itens: [
        { os_numero: 205, dias_atraso: 2, bloco: "oficina", pausada: false },
        { os_numero: 206, dias_atraso: 1, bloco: "oficina", pausada: false },
      ],
    },
    prazo_hoje: {
      total: 3,
      ja_prontas: 1,
      itens: [
        { os_numero: 212, bloco: "oficina", pausada: false },
        { os_numero: 214, bloco: "oficina", pausada: false },
      ],
    },
    prazo_amanha: {
      total: 6,
      ja_prontas: 2,
      itens: [
        { os_numero: 203, bloco: "acabamento", pausada: false },
        { os_numero: 213, bloco: "oficina", pausada: false },
        { os_numero: 220, bloco: "oficina", pausada: false },
        { os_numero: 222, bloco: "oficina", pausada: false },
      ],
    },
    abertas_sem_prazo: 1,
  },
  blocos: {
    abertas_na_parede: 27,
    entrada_arte: { total: 5, atrasadas: 0, com_cliente: 2 },
    oficina: { total: 16, nas_colunas: 15 },
    sem_maquina: {
      total: 1,
      atrasadas: 0,
      itens: [{ os_numero: 220, motivo: "generico", dias_atraso: null, pausada: false }],
    },
    acabamento: { total: 3, atrasadas: 0, retrabalho: 1 },
    saida: { total: 3, no_balcao: 1, entrega: 2, instalacao: 0, atrasadas: 0 },
  },
  maquinas: [
    {
      id: IMP,
      tipo: "plotter_impressao",
      ordem: 1,
      estado: "rodando",
      desde_em: "2026-10-01T17:05:00+00:00",
      desde_local: "14:05",
      livre_por: null,
      agora: {
        os_numero: 212,
        produto: "Lona 440g reforçada impressa",
        item: "produto",
        itens_na_os: 1,
        origem: "apontamento",
        minutos_previstos: 90,
        dias_atraso: null,
        pausada: false,
        fora_da_oficina: false,
      },
      janela: null,
      fila: {
        total: 4,
        itens: [
          {
            os_numero: 205,
            produto: "Banner com bastão e corda",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: 2,
            prazo: null,
            reserva_local: "16:00",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 214,
            produto: "Adesivo vinil branco impresso",
            item: "produto",
            itens_na_os: 2,
            dias_atraso: null,
            prazo: "hoje",
            reserva_local: "16:40",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 217,
            produto: "Adesivo perfurado (one way)",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: "sex",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 219,
            produto: "Placa PS 2mm com adesivo",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: null,
            reserva_vencida: false,
            origem: "produto",
            pausada: false,
          },
        ],
      },
      a_caminho: 2,
      reservas_vencidas: { total: 0, mais_antiga_local: null },
      ultimo_apontamento_local: "14:05",
      ultimo_apontamento_os_numero: 212,
      ultimo_job_3d_local: null,
    },
    {
      id: REC,
      tipo: "plotter_recorte",
      ordem: 2,
      estado: "reservada",
      desde_em: "2026-10-01T18:00:00+00:00",
      desde_local: "15:00",
      livre_por: null,
      agora: {
        os_numero: 213,
        produto: "Adesivo vinil recortado",
        item: "produto",
        itens_na_os: 1,
        origem: "reserva",
        minutos_previstos: 90,
        dias_atraso: null,
        pausada: false,
        fora_da_oficina: false,
      },
      janela: { inicio_local: "15:00", fim_local: "16:30" },
      fila: {
        total: 3,
        itens: [
          {
            os_numero: 214,
            produto: "Adesivo vinil recortado",
            item: "produto",
            itens_na_os: 2,
            dias_atraso: null,
            prazo: "hoje",
            reserva_local: "17:10",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 216,
            produto: "Adesivo vinil recortado",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: "sex",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 215,
            produto: "Adesivo vinil recortado",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: null,
            reserva_vencida: false,
            origem: "produto",
            pausada: true,
          },
        ],
      },
      a_caminho: 0,
      reservas_vencidas: { total: 0, mais_antiga_local: null },
      ultimo_apontamento_local: "11:50",
      ultimo_apontamento_os_numero: 204,
      ultimo_job_3d_local: null,
    },
    {
      id: CO2,
      tipo: "laser_co2",
      ordem: 3,
      estado: "bloqueada",
      desde_em: "2026-10-01T13:20:00+00:00",
      desde_local: "10:20",
      livre_por: null,
      agora: null,
      janela: { inicio_local: "10:20", fim_local: "17:00" },
      fila: {
        total: 2,
        itens: [
          {
            os_numero: 206,
            produto: "Corte a laser em MDF 3mm",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: 1,
            prazo: null,
            reserva_local: "30/09",
            reserva_vencida: true,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 221,
            produto: "Acrílico 3mm cortado a laser",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: "sex",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
        ],
      },
      a_caminho: 0,
      reservas_vencidas: { total: 1, mais_antiga_local: "30/09" },
      ultimo_apontamento_local: null,
      ultimo_apontamento_os_numero: null,
      ultimo_job_3d_local: null,
    },
    {
      id: FIB,
      tipo: "laser_fiber",
      ordem: 4,
      estado: "livre",
      desde_em: "2026-10-01T18:10:00+00:00",
      desde_local: "15:10",
      livre_por: "apontamento",
      agora: null,
      janela: null,
      fila: {
        total: 3,
        itens: [
          {
            os_numero: 222,
            produto: "Copo térmico gravado a laser",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: "amanha",
            reserva_local: "16:00",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 223,
            produto: null,
            item: "sob_medida",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: "sex",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
          {
            os_numero: 225,
            produto: "Chaveiro de metal gravado",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: null,
            reserva_vencida: false,
            origem: "produto",
            pausada: false,
          },
        ],
      },
      a_caminho: 0,
      reservas_vencidas: { total: 0, mais_antiga_local: null },
      ultimo_apontamento_local: "15:10",
      ultimo_apontamento_os_numero: 203,
      ultimo_job_3d_local: null,
    },
    {
      id: D3,
      tipo: "impressora_3d",
      ordem: 5,
      estado: "pelo_status",
      desde_em: "2026-10-01T16:10:00+00:00",
      desde_local: "13:10",
      livre_por: null,
      agora: {
        os_numero: 218,
        produto: "Impressão 3D (serviço)",
        item: "produto",
        itens_na_os: 1,
        origem: "status",
        minutos_previstos: null,
        dias_atraso: null,
        pausada: false,
        fora_da_oficina: false,
      },
      janela: null,
      fila: {
        total: 1,
        itens: [
          {
            os_numero: 224,
            produto: "Impressão 3D (serviço)",
            item: "produto",
            itens_na_os: 1,
            dias_atraso: null,
            prazo: null,
            reserva_local: "sex",
            reserva_vencida: false,
            origem: "reserva",
            pausada: false,
          },
        ],
      },
      a_caminho: 0,
      reservas_vencidas: { total: 0, mais_antiga_local: null },
      ultimo_apontamento_local: null,
      ultimo_apontamento_os_numero: null,
      ultimo_job_3d_local: null,
    },
  ],
  // A função manda também as reservas de hoje e de amanhã; a tela deixa as
  // reservas de fora do letreiro (decisão j). Aqui elas vêm como viriam.
  saidas: {
    total: 11,
    itens: [
      { tipo: "reserva", quando: "hoje", hora_local: "16:00", os_numero: 205, maquina_id: IMP },
      { tipo: "reserva", quando: "hoje", hora_local: "16:00", os_numero: 222, maquina_id: FIB },
      { tipo: "instalacao", quando: "hoje", hora_local: "16:30", os_numero: 204, maquina_id: null },
      { tipo: "reserva", quando: "hoje", hora_local: "16:40", os_numero: 214, maquina_id: IMP },
      { tipo: "reserva", quando: "hoje", hora_local: "17:10", os_numero: 214, maquina_id: REC },
      { tipo: "retirada", quando: "amanha", hora_local: null, os_numero: 211, maquina_id: null },
      { tipo: "reserva", quando: "amanha", hora_local: "08:00", os_numero: 224, maquina_id: D3 },
      { tipo: "reserva", quando: "amanha", hora_local: "08:30", os_numero: 217, maquina_id: IMP },
      { tipo: "reserva", quando: "amanha", hora_local: "09:00", os_numero: 216, maquina_id: REC },
      { tipo: "entrega", quando: "amanha", hora_local: "10:00", os_numero: 210, maquina_id: null },
      { tipo: "reserva", quando: "amanha", hora_local: "10:00", os_numero: 221, maquina_id: CO2 },
    ],
  },
  eventos: {
    ultimo: {
      id: "hist:ex-203-acab",
      tipo: "os_foi_para_acabamento",
      maquina_id: null,
      os_numero: 203,
      ocorrido_em: "2026-10-01T18:12:00+00:00",
      hora_local: "15:12",
      dia_local: "01/10",
    },
    total_de_hoje: 11,
    itens_de_hoje: [
      {
        id: "hist:ex-203-acab",
        tipo: "os_foi_para_acabamento",
        maquina_id: null,
        os_numero: 203,
        ocorrido_em: "2026-10-01T18:12:00+00:00",
        hora_local: "15:12",
        dia_local: "01/10",
      },
      {
        id: "apt-fim:ex-a3",
        tipo: "apontamento_finalizado",
        maquina_id: FIB,
        os_numero: 203,
        ocorrido_em: "2026-10-01T18:10:00+00:00",
        hora_local: "15:10",
        dia_local: "01/10",
      },
      {
        id: "apt-ini:ex-a4",
        tipo: "apontamento_iniciado",
        maquina_id: IMP,
        os_numero: 212,
        ocorrido_em: "2026-10-01T17:05:00+00:00",
        hora_local: "14:05",
        dia_local: "01/10",
      },
      {
        id: "apt-ini:ex-a3",
        tipo: "apontamento_iniciado",
        maquina_id: FIB,
        os_numero: 203,
        ocorrido_em: "2026-10-01T16:50:00+00:00",
        hora_local: "13:50",
        dia_local: "01/10",
      },
      {
        id: "hist:ex-204-pronta",
        tipo: "os_ficou_pronta",
        maquina_id: null,
        os_numero: 204,
        ocorrido_em: "2026-10-01T16:30:00+00:00",
        hora_local: "13:30",
        dia_local: "01/10",
      },
      {
        id: "hist:ex-204-acab",
        tipo: "os_foi_para_acabamento",
        maquina_id: null,
        os_numero: 204,
        ocorrido_em: "2026-10-01T15:05:00+00:00",
        hora_local: "12:05",
        dia_local: "01/10",
      },
      {
        id: "apt-fim:ex-a2",
        tipo: "apontamento_finalizado",
        maquina_id: REC,
        os_numero: 204,
        ocorrido_em: "2026-10-01T14:50:00+00:00",
        hora_local: "11:50",
        dia_local: "01/10",
      },
      {
        id: "hist:ex-219-fila",
        tipo: "os_entrou_na_fila",
        maquina_id: null,
        os_numero: 219,
        ocorrido_em: "2026-10-01T14:20:00+00:00",
        hora_local: "11:20",
        dia_local: "01/10",
      },
      {
        id: "apt-ini:ex-a2",
        tipo: "apontamento_iniciado",
        maquina_id: REC,
        os_numero: 204,
        ocorrido_em: "2026-10-01T14:00:00+00:00",
        hora_local: "11:00",
        dia_local: "01/10",
      },
      {
        id: "apt-fim:ex-a1",
        tipo: "apontamento_finalizado",
        maquina_id: IMP,
        os_numero: 204,
        ocorrido_em: "2026-10-01T13:40:00+00:00",
        hora_local: "10:40",
        dia_local: "01/10",
      },
      {
        id: "apt-ini:ex-a1",
        tipo: "apontamento_iniciado",
        maquina_id: IMP,
        os_numero: 204,
        ocorrido_em: "2026-10-01T11:20:00+00:00",
        hora_local: "08:20",
        dia_local: "01/10",
      },
    ],
  },
  consistencia: { ok: true, falhas: [], avisos: [] },
};

/* Retorno REAL de tv_painel_maquinas() em 2026-10-01 22:54 UTC (19:54 em Macapá). */
const SEM_REGISTRO = (
  id: string,
  tipo: string,
  ordem: number,
): PainelDaOficina["maquinas"][number] => ({
  id,
  tipo,
  ordem,
  estado: "sem_registro",
  desde_em: null,
  desde_local: null,
  agora: null,
  janela: null,
  fila: { total: 0, itens: [] },
  a_caminho: 0,
  reservas_vencidas: { total: 0, mais_antiga_local: null },
  ultimo_apontamento_local: null,
  ultimo_apontamento_os_numero: null,
  ultimo_job_3d_local: null,
});

export const EXEMPLO_HOJE: PainelDaOficina = {
  versao: 2,
  gerado_em: "2026-10-01T22:54:33.340051+00:00",
  hoje_local: "2026-10-01",
  fuso: "America/Belem",
  intervalo_s: 60,
  dentro_do_expediente: false,
  registro: {
    apontamentos_hoje: 0,
    apontamentos_abertos: 0,
    ultimo_apontamento_local: null,
    sem_apontamento_em_7_dias: true,
    jobs_3d_hoje: 0,
    ultimo_job_3d_local: null,
  },
  rodando: { total: 0, de: 5 },
  cartoes: {
    atrasadas: {
      total: 1,
      nas_maquinas: 0,
      fora: 1,
      itens: [{ os_numero: 49, dias_atraso: 22, bloco: "entrada_arte", pausada: false }],
    },
    prazo_hoje: { total: 0, ja_prontas: 0, itens: [] },
    prazo_amanha: { total: 0, ja_prontas: 0, itens: [] },
    abertas_sem_prazo: 1,
  },
  blocos: {
    abertas_na_parede: 2,
    entrada_arte: { total: 2, atrasadas: 1, com_cliente: 0 },
    oficina: { total: 0, nas_colunas: 0 },
    sem_maquina: { total: 0, atrasadas: 0, itens: [] },
    acabamento: { total: 0, atrasadas: 0, retrabalho: 0 },
    saida: { total: 0, no_balcao: 0, entrega: 0, instalacao: 0, atrasadas: 0 },
  },
  maquinas: [
    SEM_REGISTRO(IMP, "plotter_impressao", 1),
    SEM_REGISTRO(REC, "plotter_recorte", 2),
    SEM_REGISTRO(CO2, "laser_co2", 3),
    SEM_REGISTRO(FIB, "laser_fiber", 4),
    SEM_REGISTRO(D3, "impressora_3d", 5),
  ],
  saidas: { total: 0, itens: [] },
  eventos: { ultimo: null, total_de_hoje: 0, itens_de_hoje: [] },
  consistencia: { ok: true, falhas: [] },
};

export function painelDeExemplo(modo: ModoDeExemplo): PainelDaOficina {
  return modo === "hoje" ? EXEMPLO_HOJE : EXEMPLO_CHEIO;
}
