/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicoTokenRouteImport } from './routes/publico.$token'
import { Route as AprovarTokenRouteImport } from './routes/aprovar.$token'
import { Route as AuthenticatedWhatsappMonitorRouteImport } from './routes/_authenticated/whatsapp-monitor'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRespostasRapidasRouteImport } from './routes/_authenticated/respostas-rapidas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedProdutividade3dRouteImport } from './routes/_authenticated/produtividade-3d'
import { Route as AuthenticatedProducao3dRouteImport } from './routes/_authenticated/producao-3d'
import { Route as AuthenticatedPosVendaRouteImport } from './routes/_authenticated/pos-venda'
import { Route as AuthenticatedPortalClienteRouteImport } from './routes/_authenticated/portal-cliente'
import { Route as AuthenticatedPerdasRouteImport } from './routes/_authenticated/perdas'
import { Route as AuthenticatedOrcamento3dNovoRouteImport } from './routes/_authenticated/orcamento-3d-novo'
import { Route as AuthenticatedOcorrenciasRouteImport } from './routes/_authenticated/ocorrencias'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedMatrizPermissoesRouteImport } from './routes/_authenticated/matriz-permissoes'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedMaquinasAgendaRouteImport } from './routes/_authenticated/maquinas-agenda'
import { Route as AuthenticatedMaquinasRouteImport } from './routes/_authenticated/maquinas'
import { Route as AuthenticatedMapaSistemaRouteImport } from './routes/_authenticated/mapa-sistema'
import { Route as AuthenticatedManutencaoRouteImport } from './routes/_authenticated/manutencao'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedImpressoras3dRouteImport } from './routes/_authenticated/impressoras-3d'
import { Route as AuthenticatedImpressao3dRouteImport } from './routes/_authenticated/impressao-3d'
import { Route as AuthenticatedFluxoCaixaRouteImport } from './routes/_authenticated/fluxo-caixa'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFilamentos3dRouteImport } from './routes/_authenticated/filamentos-3d'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustosProducaoRouteImport } from './routes/_authenticated/custos-producao'
import { Route as AuthenticatedConfiguracoesEmpresaRouteImport } from './routes/_authenticated/configuracoes-empresa'
import { Route as AuthenticatedConfiguracoes3dRouteImport } from './routes/_authenticated/configuracoes-3d'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedCasosDeUsoRouteImport } from './routes/_authenticated/casos-de-uso'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedOsIndexRouteImport } from './routes/_authenticated/os.index'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated/os.$id'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated/orcamentos.$id'
import { Route as AuthenticatedOrcamento3dIdRouteImport } from './routes/_authenticated/orcamento-3d.$id'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicoTokenRoute = PublicoTokenRouteImport.update({
  id: '/publico/$token',
  path: '/publico/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovarTokenRoute = AprovarTokenRouteImport.update({
  id: '/aprovar/$token',
  path: '/aprovar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappMonitorRoute =
  AuthenticatedWhatsappMonitorRouteImport.update({
    id: '/whatsapp-monitor',
    path: '/whatsapp-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRespostasRapidasRoute =
  AuthenticatedRespostasRapidasRouteImport.update({
    id: '/respostas-rapidas',
    path: '/respostas-rapidas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutividade3dRoute =
  AuthenticatedProdutividade3dRouteImport.update({
    id: '/produtividade-3d',
    path: '/produtividade-3d',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducao3dRoute = AuthenticatedProducao3dRouteImport.update({
  id: '/producao-3d',
  path: '/producao-3d',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosVendaRoute = AuthenticatedPosVendaRouteImport.update({
  id: '/pos-venda',
  path: '/pos-venda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalClienteRoute =
  AuthenticatedPortalClienteRouteImport.update({
    id: '/portal-cliente',
    path: '/portal-cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerdasRoute = AuthenticatedPerdasRouteImport.update({
  id: '/perdas',
  path: '/perdas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamento3dNovoRoute =
  AuthenticatedOrcamento3dNovoRouteImport.update({
    id: '/orcamento-3d-novo',
    path: '/orcamento-3d-novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOcorrenciasRoute =
  AuthenticatedOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatrizPermissoesRoute =
  AuthenticatedMatrizPermissoesRouteImport.update({
    id: '/matriz-permissoes',
    path: '/matriz-permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaquinasAgendaRoute =
  AuthenticatedMaquinasAgendaRouteImport.update({
    id: '/maquinas-agenda',
    path: '/maquinas-agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaquinasRoute = AuthenticatedMaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaSistemaRoute =
  AuthenticatedMapaSistemaRouteImport.update({
    id: '/mapa-sistema',
    path: '/mapa-sistema',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManutencaoRoute = AuthenticatedManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpressoras3dRoute =
  AuthenticatedImpressoras3dRouteImport.update({
    id: '/impressoras-3d',
    path: '/impressoras-3d',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpressao3dRoute =
  AuthenticatedImpressao3dRouteImport.update({
    id: '/impressao-3d',
    path: '/impressao-3d',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFluxoCaixaRoute = AuthenticatedFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilamentos3dRoute =
  AuthenticatedFilamentos3dRouteImport.update({
    id: '/filamentos-3d',
    path: '/filamentos-3d',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustosProducaoRoute =
  AuthenticatedCustosProducaoRouteImport.update({
    id: '/custos-producao',
    path: '/custos-producao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesEmpresaRoute =
  AuthenticatedConfiguracoesEmpresaRouteImport.update({
    id: '/configuracoes-empresa',
    path: '/configuracoes-empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoes3dRoute =
  AuthenticatedConfiguracoes3dRouteImport.update({
    id: '/configuracoes-3d',
    path: '/configuracoes-3d',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasosDeUsoRoute = AuthenticatedCasosDeUsoRouteImport.update({
  id: '/casos-de-uso',
  path: '/casos-de-uso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsIndexRoute = AuthenticatedOsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/os/$id',
  path: '/os/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosIdRoute =
  AuthenticatedOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamento3dIdRoute =
  AuthenticatedOrcamento3dIdRouteImport.update({
    id: '/orcamento-3d/$id',
    path: '/orcamento-3d/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/casos-de-uso': typeof AuthenticatedCasosDeUsoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/configuracoes-3d': typeof AuthenticatedConfiguracoes3dRoute
  '/configuracoes-empresa': typeof AuthenticatedConfiguracoesEmpresaRoute
  '/custos-producao': typeof AuthenticatedCustosProducaoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/filamentos-3d': typeof AuthenticatedFilamentos3dRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/impressao-3d': typeof AuthenticatedImpressao3dRoute
  '/impressoras-3d': typeof AuthenticatedImpressoras3dRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/mapa-sistema': typeof AuthenticatedMapaSistemaRoute
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/maquinas-agenda': typeof AuthenticatedMaquinasAgendaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/matriz-permissoes': typeof AuthenticatedMatrizPermissoesRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/orcamento-3d-novo': typeof AuthenticatedOrcamento3dNovoRoute
  '/perdas': typeof AuthenticatedPerdasRoute
  '/portal-cliente': typeof AuthenticatedPortalClienteRoute
  '/pos-venda': typeof AuthenticatedPosVendaRoute
  '/producao-3d': typeof AuthenticatedProducao3dRoute
  '/produtividade-3d': typeof AuthenticatedProdutividade3dRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/whatsapp-monitor': typeof AuthenticatedWhatsappMonitorRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/publico/$token': typeof PublicoTokenRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/orcamento-3d/$id': typeof AuthenticatedOrcamento3dIdRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/os/': typeof AuthenticatedOsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/casos-de-uso': typeof AuthenticatedCasosDeUsoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/configuracoes-3d': typeof AuthenticatedConfiguracoes3dRoute
  '/configuracoes-empresa': typeof AuthenticatedConfiguracoesEmpresaRoute
  '/custos-producao': typeof AuthenticatedCustosProducaoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/filamentos-3d': typeof AuthenticatedFilamentos3dRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/impressao-3d': typeof AuthenticatedImpressao3dRoute
  '/impressoras-3d': typeof AuthenticatedImpressoras3dRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/mapa-sistema': typeof AuthenticatedMapaSistemaRoute
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/maquinas-agenda': typeof AuthenticatedMaquinasAgendaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/matriz-permissoes': typeof AuthenticatedMatrizPermissoesRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/orcamento-3d-novo': typeof AuthenticatedOrcamento3dNovoRoute
  '/perdas': typeof AuthenticatedPerdasRoute
  '/portal-cliente': typeof AuthenticatedPortalClienteRoute
  '/pos-venda': typeof AuthenticatedPosVendaRoute
  '/producao-3d': typeof AuthenticatedProducao3dRoute
  '/produtividade-3d': typeof AuthenticatedProdutividade3dRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/whatsapp-monitor': typeof AuthenticatedWhatsappMonitorRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/publico/$token': typeof PublicoTokenRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/orcamento-3d/$id': typeof AuthenticatedOrcamento3dIdRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/os': typeof AuthenticatedOsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/casos-de-uso': typeof AuthenticatedCasosDeUsoRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/configuracoes-3d': typeof AuthenticatedConfiguracoes3dRoute
  '/_authenticated/configuracoes-empresa': typeof AuthenticatedConfiguracoesEmpresaRoute
  '/_authenticated/custos-producao': typeof AuthenticatedCustosProducaoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/filamentos-3d': typeof AuthenticatedFilamentos3dRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/_authenticated/impressao-3d': typeof AuthenticatedImpressao3dRoute
  '/_authenticated/impressoras-3d': typeof AuthenticatedImpressoras3dRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/manutencao': typeof AuthenticatedManutencaoRoute
  '/_authenticated/mapa-sistema': typeof AuthenticatedMapaSistemaRoute
  '/_authenticated/maquinas': typeof AuthenticatedMaquinasRoute
  '/_authenticated/maquinas-agenda': typeof AuthenticatedMaquinasAgendaRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/matriz-permissoes': typeof AuthenticatedMatrizPermissoesRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/_authenticated/orcamento-3d-novo': typeof AuthenticatedOrcamento3dNovoRoute
  '/_authenticated/perdas': typeof AuthenticatedPerdasRoute
  '/_authenticated/portal-cliente': typeof AuthenticatedPortalClienteRoute
  '/_authenticated/pos-venda': typeof AuthenticatedPosVendaRoute
  '/_authenticated/producao-3d': typeof AuthenticatedProducao3dRoute
  '/_authenticated/produtividade-3d': typeof AuthenticatedProdutividade3dRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/whatsapp-monitor': typeof AuthenticatedWhatsappMonitorRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/publico/$token': typeof PublicoTokenRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/orcamento-3d/$id': typeof AuthenticatedOrcamento3dIdRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/os/': typeof AuthenticatedOsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/arquivos'
    | '/automacoes'
    | '/casos-de-uso'
    | '/compras'
    | '/configuracoes'
    | '/configuracoes-3d'
    | '/configuracoes-empresa'
    | '/custos-producao'
    | '/dashboard'
    | '/design'
    | '/entregas'
    | '/filamentos-3d'
    | '/financeiro'
    | '/fluxo-caixa'
    | '/impressao-3d'
    | '/impressoras-3d'
    | '/kanban'
    | '/leads'
    | '/logs'
    | '/manutencao'
    | '/mapa-sistema'
    | '/maquinas'
    | '/maquinas-agenda'
    | '/materiais'
    | '/matriz-permissoes'
    | '/movimentacoes'
    | '/ocorrencias'
    | '/orcamento-3d-novo'
    | '/perdas'
    | '/portal-cliente'
    | '/pos-venda'
    | '/producao-3d'
    | '/produtividade-3d'
    | '/produtos'
    | '/relatorios'
    | '/respostas-rapidas'
    | '/usuarios'
    | '/whatsapp'
    | '/whatsapp-monitor'
    | '/aprovar/$token'
    | '/publico/$token'
    | '/clientes/$id'
    | '/orcamento-3d/$id'
    | '/orcamentos/$id'
    | '/os/$id'
    | '/clientes/'
    | '/orcamentos/'
    | '/os/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/arquivos'
    | '/automacoes'
    | '/casos-de-uso'
    | '/compras'
    | '/configuracoes'
    | '/configuracoes-3d'
    | '/configuracoes-empresa'
    | '/custos-producao'
    | '/dashboard'
    | '/design'
    | '/entregas'
    | '/filamentos-3d'
    | '/financeiro'
    | '/fluxo-caixa'
    | '/impressao-3d'
    | '/impressoras-3d'
    | '/kanban'
    | '/leads'
    | '/logs'
    | '/manutencao'
    | '/mapa-sistema'
    | '/maquinas'
    | '/maquinas-agenda'
    | '/materiais'
    | '/matriz-permissoes'
    | '/movimentacoes'
    | '/ocorrencias'
    | '/orcamento-3d-novo'
    | '/perdas'
    | '/portal-cliente'
    | '/pos-venda'
    | '/producao-3d'
    | '/produtividade-3d'
    | '/produtos'
    | '/relatorios'
    | '/respostas-rapidas'
    | '/usuarios'
    | '/whatsapp'
    | '/whatsapp-monitor'
    | '/aprovar/$token'
    | '/publico/$token'
    | '/clientes/$id'
    | '/orcamento-3d/$id'
    | '/orcamentos/$id'
    | '/os/$id'
    | '/clientes'
    | '/orcamentos'
    | '/os'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/arquivos'
    | '/_authenticated/automacoes'
    | '/_authenticated/casos-de-uso'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/configuracoes-3d'
    | '/_authenticated/configuracoes-empresa'
    | '/_authenticated/custos-producao'
    | '/_authenticated/dashboard'
    | '/_authenticated/design'
    | '/_authenticated/entregas'
    | '/_authenticated/filamentos-3d'
    | '/_authenticated/financeiro'
    | '/_authenticated/fluxo-caixa'
    | '/_authenticated/impressao-3d'
    | '/_authenticated/impressoras-3d'
    | '/_authenticated/kanban'
    | '/_authenticated/leads'
    | '/_authenticated/logs'
    | '/_authenticated/manutencao'
    | '/_authenticated/mapa-sistema'
    | '/_authenticated/maquinas'
    | '/_authenticated/maquinas-agenda'
    | '/_authenticated/materiais'
    | '/_authenticated/matriz-permissoes'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/ocorrencias'
    | '/_authenticated/orcamento-3d-novo'
    | '/_authenticated/perdas'
    | '/_authenticated/portal-cliente'
    | '/_authenticated/pos-venda'
    | '/_authenticated/producao-3d'
    | '/_authenticated/produtividade-3d'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/respostas-rapidas'
    | '/_authenticated/usuarios'
    | '/_authenticated/whatsapp'
    | '/_authenticated/whatsapp-monitor'
    | '/aprovar/$token'
    | '/publico/$token'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/orcamento-3d/$id'
    | '/_authenticated/orcamentos/$id'
    | '/_authenticated/os/$id'
    | '/_authenticated/clientes/'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/os/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AprovarTokenRoute: typeof AprovarTokenRoute
  PublicoTokenRoute: typeof PublicoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publico/$token': {
      id: '/publico/$token'
      path: '/publico/$token'
      fullPath: '/publico/$token'
      preLoaderRoute: typeof PublicoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovar/$token': {
      id: '/aprovar/$token'
      path: '/aprovar/$token'
      fullPath: '/aprovar/$token'
      preLoaderRoute: typeof AprovarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp-monitor': {
      id: '/_authenticated/whatsapp-monitor'
      path: '/whatsapp-monitor'
      fullPath: '/whatsapp-monitor'
      preLoaderRoute: typeof AuthenticatedWhatsappMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respostas-rapidas': {
      id: '/_authenticated/respostas-rapidas'
      path: '/respostas-rapidas'
      fullPath: '/respostas-rapidas'
      preLoaderRoute: typeof AuthenticatedRespostasRapidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtividade-3d': {
      id: '/_authenticated/produtividade-3d'
      path: '/produtividade-3d'
      fullPath: '/produtividade-3d'
      preLoaderRoute: typeof AuthenticatedProdutividade3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao-3d': {
      id: '/_authenticated/producao-3d'
      path: '/producao-3d'
      fullPath: '/producao-3d'
      preLoaderRoute: typeof AuthenticatedProducao3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos-venda': {
      id: '/_authenticated/pos-venda'
      path: '/pos-venda'
      fullPath: '/pos-venda'
      preLoaderRoute: typeof AuthenticatedPosVendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-cliente': {
      id: '/_authenticated/portal-cliente'
      path: '/portal-cliente'
      fullPath: '/portal-cliente'
      preLoaderRoute: typeof AuthenticatedPortalClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perdas': {
      id: '/_authenticated/perdas'
      path: '/perdas'
      fullPath: '/perdas'
      preLoaderRoute: typeof AuthenticatedPerdasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento-3d-novo': {
      id: '/_authenticated/orcamento-3d-novo'
      path: '/orcamento-3d-novo'
      fullPath: '/orcamento-3d-novo'
      preLoaderRoute: typeof AuthenticatedOrcamento3dNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias': {
      id: '/_authenticated/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof AuthenticatedOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matriz-permissoes': {
      id: '/_authenticated/matriz-permissoes'
      path: '/matriz-permissoes'
      fullPath: '/matriz-permissoes'
      preLoaderRoute: typeof AuthenticatedMatrizPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquinas-agenda': {
      id: '/_authenticated/maquinas-agenda'
      path: '/maquinas-agenda'
      fullPath: '/maquinas-agenda'
      preLoaderRoute: typeof AuthenticatedMaquinasAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquinas': {
      id: '/_authenticated/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof AuthenticatedMaquinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa-sistema': {
      id: '/_authenticated/mapa-sistema'
      path: '/mapa-sistema'
      fullPath: '/mapa-sistema'
      preLoaderRoute: typeof AuthenticatedMapaSistemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencao': {
      id: '/_authenticated/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impressoras-3d': {
      id: '/_authenticated/impressoras-3d'
      path: '/impressoras-3d'
      fullPath: '/impressoras-3d'
      preLoaderRoute: typeof AuthenticatedImpressoras3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impressao-3d': {
      id: '/_authenticated/impressao-3d'
      path: '/impressao-3d'
      fullPath: '/impressao-3d'
      preLoaderRoute: typeof AuthenticatedImpressao3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo-caixa': {
      id: '/_authenticated/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filamentos-3d': {
      id: '/_authenticated/filamentos-3d'
      path: '/filamentos-3d'
      fullPath: '/filamentos-3d'
      preLoaderRoute: typeof AuthenticatedFilamentos3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos-producao': {
      id: '/_authenticated/custos-producao'
      path: '/custos-producao'
      fullPath: '/custos-producao'
      preLoaderRoute: typeof AuthenticatedCustosProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes-empresa': {
      id: '/_authenticated/configuracoes-empresa'
      path: '/configuracoes-empresa'
      fullPath: '/configuracoes-empresa'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes-3d': {
      id: '/_authenticated/configuracoes-3d'
      path: '/configuracoes-3d'
      fullPath: '/configuracoes-3d'
      preLoaderRoute: typeof AuthenticatedConfiguracoes3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casos-de-uso': {
      id: '/_authenticated/casos-de-uso'
      path: '/casos-de-uso'
      fullPath: '/casos-de-uso'
      preLoaderRoute: typeof AuthenticatedCasosDeUsoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/': {
      id: '/_authenticated/os/'
      path: '/os'
      fullPath: '/os/'
      preLoaderRoute: typeof AuthenticatedOsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/os/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/$id': {
      id: '/_authenticated/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento-3d/$id': {
      id: '/_authenticated/orcamento-3d/$id'
      path: '/orcamento-3d/$id'
      fullPath: '/orcamento-3d/$id'
      preLoaderRoute: typeof AuthenticatedOrcamento3dIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedCasosDeUsoRoute: typeof AuthenticatedCasosDeUsoRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConfiguracoes3dRoute: typeof AuthenticatedConfiguracoes3dRoute
  AuthenticatedConfiguracoesEmpresaRoute: typeof AuthenticatedConfiguracoesEmpresaRoute
  AuthenticatedCustosProducaoRoute: typeof AuthenticatedCustosProducaoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedFilamentos3dRoute: typeof AuthenticatedFilamentos3dRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFluxoCaixaRoute: typeof AuthenticatedFluxoCaixaRoute
  AuthenticatedImpressao3dRoute: typeof AuthenticatedImpressao3dRoute
  AuthenticatedImpressoras3dRoute: typeof AuthenticatedImpressoras3dRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedManutencaoRoute: typeof AuthenticatedManutencaoRoute
  AuthenticatedMapaSistemaRoute: typeof AuthenticatedMapaSistemaRoute
  AuthenticatedMaquinasRoute: typeof AuthenticatedMaquinasRoute
  AuthenticatedMaquinasAgendaRoute: typeof AuthenticatedMaquinasAgendaRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMatrizPermissoesRoute: typeof AuthenticatedMatrizPermissoesRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedOcorrenciasRoute: typeof AuthenticatedOcorrenciasRoute
  AuthenticatedOrcamento3dNovoRoute: typeof AuthenticatedOrcamento3dNovoRoute
  AuthenticatedPerdasRoute: typeof AuthenticatedPerdasRoute
  AuthenticatedPortalClienteRoute: typeof AuthenticatedPortalClienteRoute
  AuthenticatedPosVendaRoute: typeof AuthenticatedPosVendaRoute
  AuthenticatedProducao3dRoute: typeof AuthenticatedProducao3dRoute
  AuthenticatedProdutividade3dRoute: typeof AuthenticatedProdutividade3dRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRespostasRapidasRoute: typeof AuthenticatedRespostasRapidasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedWhatsappMonitorRoute: typeof AuthenticatedWhatsappMonitorRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedOrcamento3dIdRoute: typeof AuthenticatedOrcamento3dIdRoute
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRoute
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedOsIndexRoute: typeof AuthenticatedOsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedCasosDeUsoRoute: AuthenticatedCasosDeUsoRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConfiguracoes3dRoute: AuthenticatedConfiguracoes3dRoute,
  AuthenticatedConfiguracoesEmpresaRoute:
    AuthenticatedConfiguracoesEmpresaRoute,
  AuthenticatedCustosProducaoRoute: AuthenticatedCustosProducaoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedFilamentos3dRoute: AuthenticatedFilamentos3dRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFluxoCaixaRoute: AuthenticatedFluxoCaixaRoute,
  AuthenticatedImpressao3dRoute: AuthenticatedImpressao3dRoute,
  AuthenticatedImpressoras3dRoute: AuthenticatedImpressoras3dRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedManutencaoRoute: AuthenticatedManutencaoRoute,
  AuthenticatedMapaSistemaRoute: AuthenticatedMapaSistemaRoute,
  AuthenticatedMaquinasRoute: AuthenticatedMaquinasRoute,
  AuthenticatedMaquinasAgendaRoute: AuthenticatedMaquinasAgendaRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMatrizPermissoesRoute: AuthenticatedMatrizPermissoesRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedOcorrenciasRoute: AuthenticatedOcorrenciasRoute,
  AuthenticatedOrcamento3dNovoRoute: AuthenticatedOrcamento3dNovoRoute,
  AuthenticatedPerdasRoute: AuthenticatedPerdasRoute,
  AuthenticatedPortalClienteRoute: AuthenticatedPortalClienteRoute,
  AuthenticatedPosVendaRoute: AuthenticatedPosVendaRoute,
  AuthenticatedProducao3dRoute: AuthenticatedProducao3dRoute,
  AuthenticatedProdutividade3dRoute: AuthenticatedProdutividade3dRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRespostasRapidasRoute: AuthenticatedRespostasRapidasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedWhatsappMonitorRoute: AuthenticatedWhatsappMonitorRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedOrcamento3dIdRoute: AuthenticatedOrcamento3dIdRoute,
  AuthenticatedOrcamentosIdRoute: AuthenticatedOrcamentosIdRoute,
  AuthenticatedOsIdRoute: AuthenticatedOsIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
  AuthenticatedOsIndexRoute: AuthenticatedOsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AprovarTokenRoute: AprovarTokenRoute,
  PublicoTokenRoute: PublicoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
