/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicoTokenRouteImport } from './routes/publico.$token'
import { Route as AuthenticatedWhatsappMonitorRouteImport } from './routes/_authenticated/whatsapp-monitor'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRespostasRapidasRouteImport } from './routes/_authenticated/respostas-rapidas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedProducao3dRouteImport } from './routes/_authenticated/producao-3d'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedPosVendaRouteImport } from './routes/_authenticated/pos-venda'
import { Route as AuthenticatedPortalClienteRouteImport } from './routes/_authenticated/portal-cliente'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedOcorrenciasRouteImport } from './routes/_authenticated/ocorrencias'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedMaquinasAgendaRouteImport } from './routes/_authenticated/maquinas-agenda'
import { Route as AuthenticatedMaquinasRouteImport } from './routes/_authenticated/maquinas'
import { Route as AuthenticatedManutencaoRouteImport } from './routes/_authenticated/manutencao'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedImpressao3dRouteImport } from './routes/_authenticated/impressao-3d'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated/os.$id'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated/orcamentos.$id'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicoTokenRoute = PublicoTokenRouteImport.update({
  id: '/publico/$token',
  path: '/publico/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappMonitorRoute =
  AuthenticatedWhatsappMonitorRouteImport.update({
    id: '/whatsapp-monitor',
    path: '/whatsapp-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRespostasRapidasRoute =
  AuthenticatedRespostasRapidasRouteImport.update({
    id: '/respostas-rapidas',
    path: '/respostas-rapidas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducao3dRoute = AuthenticatedProducao3dRouteImport.update({
  id: '/producao-3d',
  path: '/producao-3d',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosVendaRoute = AuthenticatedPosVendaRouteImport.update({
  id: '/pos-venda',
  path: '/pos-venda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalClienteRoute =
  AuthenticatedPortalClienteRouteImport.update({
    id: '/portal-cliente',
    path: '/portal-cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcorrenciasRoute =
  AuthenticatedOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaquinasAgendaRoute =
  AuthenticatedMaquinasAgendaRouteImport.update({
    id: '/maquinas-agenda',
    path: '/maquinas-agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaquinasRoute = AuthenticatedMaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencaoRoute = AuthenticatedManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpressao3dRoute =
  AuthenticatedImpressao3dRouteImport.update({
    id: '/impressao-3d',
    path: '/impressao-3d',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOrcamentosIdRoute =
  AuthenticatedOrcamentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOrcamentosRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/impressao-3d': typeof AuthenticatedImpressao3dRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/maquinas-agenda': typeof AuthenticatedMaquinasAgendaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRouteWithChildren
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/portal-cliente': typeof AuthenticatedPortalClienteRoute
  '/pos-venda': typeof AuthenticatedPosVendaRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/producao-3d': typeof AuthenticatedProducao3dRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/whatsapp-monitor': typeof AuthenticatedWhatsappMonitorRoute
  '/publico/$token': typeof PublicoTokenRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/impressao-3d': typeof AuthenticatedImpressao3dRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/maquinas-agenda': typeof AuthenticatedMaquinasAgendaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRouteWithChildren
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/portal-cliente': typeof AuthenticatedPortalClienteRoute
  '/pos-venda': typeof AuthenticatedPosVendaRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/producao-3d': typeof AuthenticatedProducao3dRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/whatsapp-monitor': typeof AuthenticatedWhatsappMonitorRoute
  '/publico/$token': typeof PublicoTokenRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/impressao-3d': typeof AuthenticatedImpressao3dRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/manutencao': typeof AuthenticatedManutencaoRoute
  '/_authenticated/maquinas': typeof AuthenticatedMaquinasRoute
  '/_authenticated/maquinas-agenda': typeof AuthenticatedMaquinasAgendaRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRouteWithChildren
  '/_authenticated/os': typeof AuthenticatedOsRouteWithChildren
  '/_authenticated/portal-cliente': typeof AuthenticatedPortalClienteRoute
  '/_authenticated/pos-venda': typeof AuthenticatedPosVendaRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/producao-3d': typeof AuthenticatedProducao3dRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/whatsapp-monitor': typeof AuthenticatedWhatsappMonitorRoute
  '/publico/$token': typeof PublicoTokenRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/arquivos'
    | '/automacoes'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/design'
    | '/entregas'
    | '/financeiro'
    | '/impressao-3d'
    | '/kanban'
    | '/leads'
    | '/logs'
    | '/manutencao'
    | '/maquinas'
    | '/maquinas-agenda'
    | '/materiais'
    | '/movimentacoes'
    | '/ocorrencias'
    | '/orcamentos'
    | '/os'
    | '/portal-cliente'
    | '/pos-venda'
    | '/precificacao'
    | '/producao-3d'
    | '/produtos'
    | '/relatorios'
    | '/respostas-rapidas'
    | '/usuarios'
    | '/whatsapp'
    | '/whatsapp-monitor'
    | '/publico/$token'
    | '/clientes/$id'
    | '/orcamentos/$id'
    | '/os/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/arquivos'
    | '/automacoes'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/design'
    | '/entregas'
    | '/financeiro'
    | '/impressao-3d'
    | '/kanban'
    | '/leads'
    | '/logs'
    | '/manutencao'
    | '/maquinas'
    | '/maquinas-agenda'
    | '/materiais'
    | '/movimentacoes'
    | '/ocorrencias'
    | '/orcamentos'
    | '/os'
    | '/portal-cliente'
    | '/pos-venda'
    | '/precificacao'
    | '/producao-3d'
    | '/produtos'
    | '/relatorios'
    | '/respostas-rapidas'
    | '/usuarios'
    | '/whatsapp'
    | '/whatsapp-monitor'
    | '/publico/$token'
    | '/clientes/$id'
    | '/orcamentos/$id'
    | '/os/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/arquivos'
    | '/_authenticated/automacoes'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/design'
    | '/_authenticated/entregas'
    | '/_authenticated/financeiro'
    | '/_authenticated/impressao-3d'
    | '/_authenticated/kanban'
    | '/_authenticated/leads'
    | '/_authenticated/logs'
    | '/_authenticated/manutencao'
    | '/_authenticated/maquinas'
    | '/_authenticated/maquinas-agenda'
    | '/_authenticated/materiais'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/ocorrencias'
    | '/_authenticated/orcamentos'
    | '/_authenticated/os'
    | '/_authenticated/portal-cliente'
    | '/_authenticated/pos-venda'
    | '/_authenticated/precificacao'
    | '/_authenticated/producao-3d'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/respostas-rapidas'
    | '/_authenticated/usuarios'
    | '/_authenticated/whatsapp'
    | '/_authenticated/whatsapp-monitor'
    | '/publico/$token'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/orcamentos/$id'
    | '/_authenticated/os/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PublicoTokenRoute: typeof PublicoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publico/$token': {
      id: '/publico/$token'
      path: '/publico/$token'
      fullPath: '/publico/$token'
      preLoaderRoute: typeof PublicoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp-monitor': {
      id: '/_authenticated/whatsapp-monitor'
      path: '/whatsapp-monitor'
      fullPath: '/whatsapp-monitor'
      preLoaderRoute: typeof AuthenticatedWhatsappMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respostas-rapidas': {
      id: '/_authenticated/respostas-rapidas'
      path: '/respostas-rapidas'
      fullPath: '/respostas-rapidas'
      preLoaderRoute: typeof AuthenticatedRespostasRapidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao-3d': {
      id: '/_authenticated/producao-3d'
      path: '/producao-3d'
      fullPath: '/producao-3d'
      preLoaderRoute: typeof AuthenticatedProducao3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos-venda': {
      id: '/_authenticated/pos-venda'
      path: '/pos-venda'
      fullPath: '/pos-venda'
      preLoaderRoute: typeof AuthenticatedPosVendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-cliente': {
      id: '/_authenticated/portal-cliente'
      path: '/portal-cliente'
      fullPath: '/portal-cliente'
      preLoaderRoute: typeof AuthenticatedPortalClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias': {
      id: '/_authenticated/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof AuthenticatedOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquinas-agenda': {
      id: '/_authenticated/maquinas-agenda'
      path: '/maquinas-agenda'
      fullPath: '/maquinas-agenda'
      preLoaderRoute: typeof AuthenticatedMaquinasAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquinas': {
      id: '/_authenticated/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof AuthenticatedMaquinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencao': {
      id: '/_authenticated/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impressao-3d': {
      id: '/_authenticated/impressao-3d'
      path: '/impressao-3d'
      fullPath: '/impressao-3d'
      preLoaderRoute: typeof AuthenticatedImpressao3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/orcamentos/$id': {
      id: '/_authenticated/orcamentos/$id'
      path: '/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedOrcamentosRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedOrcamentosRouteChildren {
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRoute
}

const AuthenticatedOrcamentosRouteChildren: AuthenticatedOrcamentosRouteChildren =
  {
    AuthenticatedOrcamentosIdRoute: AuthenticatedOrcamentosIdRoute,
  }

const AuthenticatedOrcamentosRouteWithChildren =
  AuthenticatedOrcamentosRoute._addFileChildren(
    AuthenticatedOrcamentosRouteChildren,
  )

interface AuthenticatedOsRouteChildren {
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
}

const AuthenticatedOsRouteChildren: AuthenticatedOsRouteChildren = {
  AuthenticatedOsIdRoute: AuthenticatedOsIdRoute,
}

const AuthenticatedOsRouteWithChildren = AuthenticatedOsRoute._addFileChildren(
  AuthenticatedOsRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedImpressao3dRoute: typeof AuthenticatedImpressao3dRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedManutencaoRoute: typeof AuthenticatedManutencaoRoute
  AuthenticatedMaquinasRoute: typeof AuthenticatedMaquinasRoute
  AuthenticatedMaquinasAgendaRoute: typeof AuthenticatedMaquinasAgendaRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedOcorrenciasRoute: typeof AuthenticatedOcorrenciasRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRouteWithChildren
  AuthenticatedOsRoute: typeof AuthenticatedOsRouteWithChildren
  AuthenticatedPortalClienteRoute: typeof AuthenticatedPortalClienteRoute
  AuthenticatedPosVendaRoute: typeof AuthenticatedPosVendaRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedProducao3dRoute: typeof AuthenticatedProducao3dRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRespostasRapidasRoute: typeof AuthenticatedRespostasRapidasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedWhatsappMonitorRoute: typeof AuthenticatedWhatsappMonitorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedImpressao3dRoute: AuthenticatedImpressao3dRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedManutencaoRoute: AuthenticatedManutencaoRoute,
  AuthenticatedMaquinasRoute: AuthenticatedMaquinasRoute,
  AuthenticatedMaquinasAgendaRoute: AuthenticatedMaquinasAgendaRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedOcorrenciasRoute: AuthenticatedOcorrenciasRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRouteWithChildren,
  AuthenticatedOsRoute: AuthenticatedOsRouteWithChildren,
  AuthenticatedPortalClienteRoute: AuthenticatedPortalClienteRoute,
  AuthenticatedPosVendaRoute: AuthenticatedPosVendaRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedProducao3dRoute: AuthenticatedProducao3dRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRespostasRapidasRoute: AuthenticatedRespostasRapidasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedWhatsappMonitorRoute: AuthenticatedWhatsappMonitorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PublicoTokenRoute: PublicoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
